INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco detox de couve com abacaxi ', '3 folhas de couve, 3 rodelas de gengibre,2 fatias de abacaxi congelado, Chia a gosto, 200 ml de água (ou água de coco),Suco de 1/2 limão', 'Reúna todos os ingredientes, Coloque todos os ingredientes no liquidificador e bata por cerca de 5 minutos, Suco detox de couve com abacaxi, Transfira o suco para um copo e, caso queira, adoce com mel. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco verde com ora-pro-nóbis', '4 maçãs, 200 ml de água, 6 folhas de azedinha, 8 folhas de ora-pro-nóbis, 1 colher de sobremesa de gengibre fresco picado', 'Bata todos os ingredientes no liquidificador até virar um suco bem grosso, Coe no saco de voil ou passe por uma peneira bem fina, Está pronto para beber! . ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco verde digestivo ', '1 fatia de abacaxi, Suco de 1 limão, Folhas de hortelã a gosto, 1/2 folha de couve, 200 ml de água de coco (natural)', 'Separe e corte os ingredientes sólidos em pedaços menores, para triturar melhor, Coloque todos os ingredientes no liquidificador e bata até ficar homogêneo. Passe para um copo e coloque gelo. Pode usar uma peneira. Agora é só servir. Bom apetite. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco de maçã com gengibre  ', '4 maçãs cortadas em pedaços (pode ser gala, fuji ou red), Cerca de 300 ml de água, 1 pedaço de gengibre descascado', 'Coloque no liquidificador, a maçã, a água e bata até ficar uniforme., Adicione o gengibre e bata por mais 10 segundos., Agora é só servir. Bom apetite ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco detox de beterraba   ', '300 ml de água gelada, 1 beterraba pequena, crua e em pedaços, Sumo de 1 limão, 1 colher de chá de mel (opcional), ' , ' Em um liquidificador, coloque todos os ingredientes e bata até misturar bem. Transfira para um copo e adicione gelo. Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco vermelho pré-treino', '100 gramas de beterraba, 100 gramas de framboesa, 20 gramas de biomassa de banana verde, 200 ml água', '    Em um liquidificador, coloque a beterraba sem casca e cortada em cubos, a framboesa, a biomassa, a água gelada e bata muito bem. Sirva bem geladinho. Aproveite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco de laranja e cenoura ', 'Suco de 12 laranjas, 1 cenoura (com casca), 1 colher de sopa de açúcar', ' Coloque tudo no liquidificador e bata até ficar homogêneo. Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco diurético de melancia ', '1 rodela de gengibre, 1 fatia de melancia, 200 ml de água de coco', 'No liquidificador, bata o gengibre com a melancia e a água de coco até obter um líquido homogêneo. Sirva sem coar e adoçar logo em seguida. Aproveite sua bebida..', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco de capim-cidreira ', '1 xícara de chá de capim-cidreira picado, 1/2 xícara de chá de folhas de hortelã, 200 ml de água gelada, Suco de 1/2 limão, 1 pedaço pequeno de gengibre', ' Coloque todos os ingredientes no liquidificador e bata até ficar homogêneo. Coe o suco e transfira para uma jarra. Acrescente e gelo no copo e sirva! Aproveite sua bebida.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Chá-verde com abacaxi e laranja ', '1 litro de água filtrada, 2 saquinhos de chá-verde, 1/2 abacaxi cortado em pedaços, Um pedaço pequeno de gengibre, Folhas de hortelã, 1/2 laranja-lima cortada em rodelas, Mel a gosto, Gelo a gosto', 'Ferva a água em uma leiteira. Assim que ferver, desligue o fogo, adicione os saquinhos de chá-verde, tampe e deixe descansar por cerca de 30 minutos. Acrescente o restante dos ingredientes, misture bem e leve para a geladeira até gelar. Agora é só servir! Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Chá gelado com casca de abacaxi  ', 'Casca de um abacaxi, 500 ml de água, 1/2 abacaxi em pedaços, 1 ramo de hortelã, Suco de 1 limão-taiti', 'Separe todos os ingredientes;Corte as cascas do abacaxi;Coloque a água em uma panela grande com as cascas e leve ao fogo; Deixe ferver de 3 a 5 minutos; Coe em uma peneira e passe para uma jarra de servir; Na jarra, adicione o ramo de hortelã, o suco de limão e os pedaços de abacaxi; Espere esfriar e adicione gelo; Agora é só servir! ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Chá de maçã com canela  ', 'Casca de 2 maçãs grandes; 1 canela em pau; 1/2 l de água', 'Lave bem as maçãs, descasque e coloque as cascas em uma forma; Asse em forno preaquecido a 180 °C por meia hora; Não se esqueça de mexer as cascas a cada dez minutos.; Retire do forno e transfira para uma panela com a canela e a água; Deixe ferver por cinco minutos; Desligue o fogo e deixe descasar por cinco minutos antes de servir.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de abobrinha com pesto de hortelã   ', 'Casca de 2 maçãs grandes; 1 canela em pau; 1/2 l de água' '1/2 xícara de chá de folhas de hortelã; 3/4 de xícara de chá de azeite; 1/4 de xícara de chá de parmesão ralado; 2 dentes de alho; 1/4 de xícara de chá de nozes; Sal a gosto; Pimenta a gosto; 1 abobrinha grande; Flor de sal a gosto; Brotos de couve a gosto','No liquidificador, coloque a hortelã, o azeite, o parmesão, o alho, as nozes, o sal, a pimenta e bata até obter um creme homogêneo. Reserve; Fatia a abobrinha em rodelas finas; Acomode a abobrinha em uma frigideira com azeite e deixe grelhar; Disponha as rodelas em um prato e despeje o molho por cima; Finalize com a flor de sal e os brotos de couve ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Quinoa com frango e legumes', '1 xícara de chá de quinoa crua; 2 xícaras de chá de água filtrada; 1 cenoura picada; 1 chuchu picado; 1 colher de chá sal; 200 gramas de filé de peito de frango em tirinhas; Suco de 1 limão; 1 colher de sopa vinagre de maçã; 1 colher de chá sal; 1 colher de sopa manteiga ou azeite', ' Reúna todos os ingredientes;  Higienize bem a quinoa e descarte a água. Reserve;  Em um recipiente, adicione o frango, o suco de limão, o vinagre, o sal, misture bem e deixe marinar na geladeira;  Em uma panela, ferva a água, coloque a quinoa, o sal e deixe cozinhar, em fogo baixo, com a panela semi tampada até a água secar. Reserve;  Cozinhe, também, a cenoura e o chuchu até ficarem al dente. Reserve;  Em uma frigideira, doure o frango na manteiga (ou no azeite);  Em uma travessa grande, junte tudo: o frango, a quinoa, os legumes cozidos e misture bem;  Agora é só servir. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de abacate com milho ', '½ cebola roxa cortada no formato de meia-lua; 2 tomates médios maduros cortados em cubos; ½ xícara de chá de milho cozido; 1 abacate pequeno cortado em cubos; Suco de meio limão; Sal a gosto; Azeite de oliva a gosto; Alface lisa a gosto, ', 'Reúna todos os ingredientes;  Coloque as cebolas, os tomates, o milho e o abacate em uma tigela;  Acrescente o suco de limão, principalmente sobre os pedaços de abacate para que eles não oxidem (escureçam); na sequência, adicione o sal, o azeite de oliva e misture;  Forre uma travessa com folhas de alface, coloque a salada temperada sobre elas e sirva na sequência. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada primavera simples ','1 maço de alface americana; 1 maço de alface crespa; 1 xícara de chá de tomate-cereja (cortados ao meio); 1 xícara de chá de palmito pupunha cortados; 1 manga picada; Sal, azeite e orégano a gosto', 'Reúna todos os ingredientes;  Pique as folhas de alface com as mãos grosseiramente e transfira para um recipiente grande;  Adicione o tomate-cereja, o palmito, a manga, tempere com sal, azeite, orégano e misture bem;  Agora é só servir.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada no pote','1/2 cenoura ralada; 1/2 xícara de beterraba ralada; 3 colheres de sopa de milho; 1/2 xícara de batata-palha; 6 tomates cereja; Folhas: alface roxa, alface americana e rúcula 1/3 de uma xícara de azeite de oliva; 1/2 colher de sobremesa de orégano; 1 pitada de sal; Fique à vontade para acrescentar outros temperos de sua preferência (vinagre, limão, alho, chimichurri)', 'Primeiro, misture bem os ingredientes do molho e coloque-o no pote de sua preferência (o mesmo em que montará a salada), se preferir, deixe-o em um recipiente à parte e junte a salada quando for comer; Em seguida, coloque a cenoura e, por cima, a beterraba; Depois, acrescente o tomate cereja, o milho e a batata-palha por cima; Por último, coloque as folhas; Na hora de comer, agite o pote, ou acrescente o molho, e está pronto', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de folhas verdes  ','Mix de folhas verdes (alfaces de diferentes tipos, rúcula, couve – o que preferir); 200 gramas de tomate cereja; 1 maçã; 1 carambola; 1 romã; Cebolinha a gosto; 1 copo de iogurte natural; Mostarda Dijon a gosto; Azeite de oliva a gosto; Vinagre de framboesa a gosto; Sal rosa a gosto ', 'Lave bem todos os ingredientes da forma como você preferir. Uma dica é deixar tudo de molho em uma solução com vinagre, para desinfetar; Caso queira, rasgue as folhas em pedaços menores. É mais fácil organizar na travessa, fica bonito no prato e é mais fácil de comer; Corte a maçã e a carambola em fatias; Corte a cebolinha em pedaços pequenos; Abra a romã e separe os bagos; Misture tudo em uma travessa, colocando primeiro as folhas verdes, depois o restante dos ingredientes. Detalhe: o tomate cereja não será cortado nesta receita; Reserve a salada enquanto você prepara o molho.     Coloque o iogurte em um recipiente fundo o bastante para caberem todos os ingredientes; Coloque os outros ingredientes um a um e teste o sabor; As quantidades podem variar de acordo com a preferência; Recomenda-se que o molho seja deixado em um potinho à parte e seja colocado sobre a salada apenas na hora de servir; Bom apetite!.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Tabule de quinoa ','1 xícara de chá de quinoa em grãos; 1 pepino; 1 tomate; 1/2 cebola; 1/2 xícara de chá de hortelã; 3 colheres de sopa de azeite;  1/2 laranja; 2 rabanetes;  1 colher de sopa de suco de limão; 1 colher de sopa de aceto balsâmico; 1 dente de alho; Sal a gosto; 6 folhas de alface americana; Tomatinhos a gosto; rotos de hortelã a gosto', 'Lave bem a quinoa e deixe de molho de um dia para o outro na geladeira; Cozinhe por dez minutos e escorra bem a água; Coloque em uma travessa e junte todos os ingredientes bem picadinhos; Sirva gelada.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de grão-de-bico simples  ','1 e ½ xícara de chá de grão-de-bico cozido; ½ xícara de chá de tomate picado; ¼ de xícara de chá de cebola picada; Salsinha a gosto; 1 colher de sopa de suco de limão; ½ colher de chá de sal; Azeite a gosto,', ' Reúna todos os ingredientes;  Coloque todos os ingredientes em uma tigela, e misture para pegar bem o tempero;  Coloque a salada na geladeira, e deixe por no mínimo 1 hora;  Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Frango empanado sem farinha   ','500 g de peito de frango Sal e pimenta-do-reino a gosto; 1 ovo; 60 g de queijo parmesão ralado', '  Reúna todos os ingredientes;  Corte o peito de frango em filés e tempere-os com sal e pimenta;  Coloque o ovo em um prato e bata-o levemente; em outro, disponha o queijo ralado;  Passe os filés no ovo batido e depois no parmesão;  Asse-os em forno pré-aquecido a 200 °C por cerca de 30 minutos ou até dourar;  Agora é só servir. Bom apetite!', 1);
