INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco detox de couve com abacaxi ', '3 folhas de couve, 3 rodelas de gengibre,2 fatias de abacaxi congelado, Chia a gosto, 200 ml de água (ou água de coco),Suco de 1/2 limão', 'Reúna todos os ingredientes, Coloque todos os ingredientes no liquidificador e bata por cerca de 5 minutos, Suco detox de couve com abacaxi, Transfira o suco para um copo e, caso queira, adoce com mel. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco verde com ora-pro-nóbis', '4 maçãs, 200 ml de água, 6 folhas de azedinha, 8 folhas de ora-pro-nóbis, 1 colher de sobremesa de gengibre fresco picado', 'Bata todos os ingredientes no liquidificador até virar um suco bem grosso, Coe no saco de voil ou passe por uma peneira bem fina, Está pronto para beber! . ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco verde digestivo ', '1 fatia de abacaxi, Suco de 1 limão, Folhas de hortelã a gosto, 1/2 folha de couve, 200 ml de água de coco (natural)', 'Separe e corte os ingredientes sólidos em pedaços menores, para triturar melhor, Coloque todos os ingredientes no liquidificador e bata até ficar homogêneo. Passe para um copo e coloque gelo. Pode usar uma peneira. Agora é só servir. Bom apetite. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco de maçã com gengibre  ', '4 maçãs cortadas em pedaços (pode ser gala, fuji ou red), Cerca de 300 ml de água, 1 pedaço de gengibre descascado', 'Coloque no liquidificador, a maçã, a água e bata até ficar uniforme., Adicione o gengibre e bata por mais 10 segundos., Agora é só servir. Bom apetite ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco detox de beterraba   ', '300 ml de água gelada, 1 beterraba pequena, crua e em pedaços, Sumo de 1 limão, 1 colher de chá de mel (opcional), ' , ' Em um liquidificador, coloque todos os ingredientes e bata até misturar bem. Transfira para um copo e adicione gelo. Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco vermelho pré-treino', '100 gramas de beterraba, 100 gramas de framboesa, 20 gramas de biomassa de banana verde, 200 ml água', '    Em um liquidificador, coloque a beterraba sem casca e cortada em cubos, a framboesa, a biomassa, a água gelada e bata muito bem. Sirva bem geladinho. Aproveite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco de laranja e cenoura ', 'Suco de 12 laranjas, 1 cenoura (com casca), 1 colher de sopa de açúcar', ' Coloque tudo no liquidificador e bata até ficar homogêneo. Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco diurético de melancia ', '1 rodela de gengibre, 1 fatia de melancia, 200 ml de água de coco', 'No liquidificador, bata o gengibre com a melancia e a água de coco até obter um líquido homogêneo. Sirva sem coar e adoçar logo em seguida. Aproveite sua bebida..', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Suco de capim-cidreira ', '1 xícara de chá de capim-cidreira picado, 1/2 xícara de chá de folhas de hortelã, 200 ml de água gelada, Suco de 1/2 limão, 1 pedaço pequeno de gengibre', ' Coloque todos os ingredientes no liquidificador e bata até ficar homogêneo. Coe o suco e transfira para uma jarra. Acrescente e gelo no copo e sirva! Aproveite sua bebida.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Chá-verde com abacaxi e laranja ', '1 litro de água filtrada, 2 saquinhos de chá-verde, 1/2 abacaxi cortado em pedaços, Um pedaço pequeno de gengibre, Folhas de hortelã, 1/2 laranja-lima cortada em rodelas, Mel a gosto, Gelo a gosto', 'Ferva a água em uma leiteira. Assim que ferver, desligue o fogo, adicione os saquinhos de chá-verde, tampe e deixe descansar por cerca de 30 minutos. Acrescente o restante dos ingredientes, misture bem e leve para a geladeira até gelar. Agora é só servir! Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Chá gelado com casca de abacaxi  ', 'Casca de um abacaxi, 500 ml de água, 1/2 abacaxi em pedaços, 1 ramo de hortelã, Suco de 1 limão-taiti', 'Separe todos os ingredientes;Corte as cascas do abacaxi;Coloque a água em uma panela grande com as cascas e leve ao fogo; Deixe ferver de 3 a 5 minutos; Coe em uma peneira e passe para uma jarra de servir; Na jarra, adicione o ramo de hortelã, o suco de limão e os pedaços de abacaxi; Espere esfriar e adicione gelo; Agora é só servir! ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Chá de maçã com canela  ', 'Casca de 2 maçãs grandes; 1 canela em pau; 1/2 l de água', 'Lave bem as maçãs, descasque e coloque as cascas em uma forma; Asse em forno preaquecido a 180 °C por meia hora; Não se esqueça de mexer as cascas a cada dez minutos.; Retire do forno e transfira para uma panela com a canela e a água; Deixe ferver por cinco minutos; Desligue o fogo e deixe descasar por cinco minutos antes de servir.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de abobrinha com pesto de hortelã   ', 'Casca de 2 maçãs grandes; 1 canela em pau; 1/2 l de água' '1/2 xícara de chá de folhas de hortelã; 3/4 de xícara de chá de azeite; 1/4 de xícara de chá de parmesão ralado; 2 dentes de alho; 1/4 de xícara de chá de nozes; Sal a gosto; Pimenta a gosto; 1 abobrinha grande; Flor de sal a gosto; Brotos de couve a gosto','No liquidificador, coloque a hortelã, o azeite, o parmesão, o alho, as nozes, o sal, a pimenta e bata até obter um creme homogêneo. Reserve; Fatia a abobrinha em rodelas finas; Acomode a abobrinha em uma frigideira com azeite e deixe grelhar; Disponha as rodelas em um prato e despeje o molho por cima; Finalize com a flor de sal e os brotos de couve ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Quinoa com frango e legumes', '1 xícara de chá de quinoa crua; 2 xícaras de chá de água filtrada; 1 cenoura picada; 1 chuchu picado; 1 colher de chá sal; 200 gramas de filé de peito de frango em tirinhas; Suco de 1 limão; 1 colher de sopa vinagre de maçã; 1 colher de chá sal; 1 colher de sopa manteiga ou azeite', ' Reúna todos os ingredientes;  Higienize bem a quinoa e descarte a água. Reserve;  Em um recipiente, adicione o frango, o suco de limão, o vinagre, o sal, misture bem e deixe marinar na geladeira;  Em uma panela, ferva a água, coloque a quinoa, o sal e deixe cozinhar, em fogo baixo, com a panela semi tampada até a água secar. Reserve;  Cozinhe, também, a cenoura e o chuchu até ficarem al dente. Reserve;  Em uma frigideira, doure o frango na manteiga (ou no azeite);  Em uma travessa grande, junte tudo: o frango, a quinoa, os legumes cozidos e misture bem;  Agora é só servir. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de abacate com milho ', '½ cebola roxa cortada no formato de meia-lua; 2 tomates médios maduros cortados em cubos; ½ xícara de chá de milho cozido; 1 abacate pequeno cortado em cubos; Suco de meio limão; Sal a gosto; Azeite de oliva a gosto; Alface lisa a gosto, ', 'Reúna todos os ingredientes;  Coloque as cebolas, os tomates, o milho e o abacate em uma tigela;  Acrescente o suco de limão, principalmente sobre os pedaços de abacate para que eles não oxidem (escureçam); na sequência, adicione o sal, o azeite de oliva e misture;  Forre uma travessa com folhas de alface, coloque a salada temperada sobre elas e sirva na sequência. ', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada primavera simples ','1 maço de alface americana; 1 maço de alface crespa; 1 xícara de chá de tomate-cereja (cortados ao meio); 1 xícara de chá de palmito pupunha cortados; 1 manga picada; Sal, azeite e orégano a gosto', 'Reúna todos os ingredientes;  Pique as folhas de alface com as mãos grosseiramente e transfira para um recipiente grande;  Adicione o tomate-cereja, o palmito, a manga, tempere com sal, azeite, orégano e misture bem;  Agora é só servir.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada no pote','1/2 cenoura ralada; 1/2 xícara de beterraba ralada; 3 colheres de sopa de milho; 1/2 xícara de batata-palha; 6 tomates cereja; Folhas: alface roxa, alface americana e rúcula 1/3 de uma xícara de azeite de oliva; 1/2 colher de sobremesa de orégano; 1 pitada de sal; Fique à vontade para acrescentar outros temperos de sua preferência (vinagre, limão, alho, chimichurri)', 'Primeiro, misture bem os ingredientes do molho e coloque-o no pote de sua preferência (o mesmo em que montará a salada), se preferir, deixe-o em um recipiente à parte e junte a salada quando for comer; Em seguida, coloque a cenoura e, por cima, a beterraba; Depois, acrescente o tomate cereja, o milho e a batata-palha por cima; Por último, coloque as folhas; Na hora de comer, agite o pote, ou acrescente o molho, e está pronto', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de folhas verdes  ','Mix de folhas verdes (alfaces de diferentes tipos, rúcula, couve – o que preferir); 200 gramas de tomate cereja; 1 maçã; 1 carambola; 1 romã; Cebolinha a gosto; 1 copo de iogurte natural; Mostarda Dijon a gosto; Azeite de oliva a gosto; Vinagre de framboesa a gosto; Sal rosa a gosto ', 'Lave bem todos os ingredientes da forma como você preferir. Uma dica é deixar tudo de molho em uma solução com vinagre, para desinfetar; Caso queira, rasgue as folhas em pedaços menores. É mais fácil organizar na travessa, fica bonito no prato e é mais fácil de comer; Corte a maçã e a carambola em fatias; Corte a cebolinha em pedaços pequenos; Abra a romã e separe os bagos; Misture tudo em uma travessa, colocando primeiro as folhas verdes, depois o restante dos ingredientes. Detalhe: o tomate cereja não será cortado nesta receita; Reserve a salada enquanto você prepara o molho.     Coloque o iogurte em um recipiente fundo o bastante para caberem todos os ingredientes; Coloque os outros ingredientes um a um e teste o sabor; As quantidades podem variar de acordo com a preferência; Recomenda-se que o molho seja deixado em um potinho à parte e seja colocado sobre a salada apenas na hora de servir; Bom apetite!.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Tabule de quinoa ','1 xícara de chá de quinoa em grãos; 1 pepino; 1 tomate; 1/2 cebola; 1/2 xícara de chá de hortelã; 3 colheres de sopa de azeite;  1/2 laranja; 2 rabanetes;  1 colher de sopa de suco de limão; 1 colher de sopa de aceto balsâmico; 1 dente de alho; Sal a gosto; 6 folhas de alface americana; Tomatinhos a gosto; rotos de hortelã a gosto', 'Lave bem a quinoa e deixe de molho de um dia para o outro na geladeira; Cozinhe por dez minutos e escorra bem a água; Coloque em uma travessa e junte todos os ingredientes bem picadinhos; Sirva gelada.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Salada de grão-de-bico simples  ','1 e ½ xícara de chá de grão-de-bico cozido; ½ xícara de chá de tomate picado; ¼ de xícara de chá de cebola picada; Salsinha a gosto; 1 colher de sopa de suco de limão; ½ colher de chá de sal; Azeite a gosto,', ' Reúna todos os ingredientes;  Coloque todos os ingredientes em uma tigela, e misture para pegar bem o tempero;  Coloque a salada na geladeira, e deixe por no mínimo 1 hora;  Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Frango empanado sem farinha   ','500 g de peito de frango Sal e pimenta-do-reino a gosto; 1 ovo; 60 g de queijo parmesão ralado', '  Reúna todos os ingredientes;  Corte o peito de frango em filés e tempere-os com sal e pimenta;  Coloque o ovo em um prato e bata-o levemente; em outro, disponha o queijo ralado;  Passe os filés no ovo batido e depois no parmesão;  Asse-os em forno pré-aquecido a 200 °C por cerca de 30 minutos ou até dourar;  Agora é só servir. Bom apetite!', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Ceviche de salmão   ','1500 gramas de filé de salmão resfriado, Sal a gosto, 1 cebola roxa, 1/2 pimenta-dedo-de-moça, 1/2 xícara de chá de azeite, 3 limões, 1 colher de sopa de shoyu, Coentro a gosto, Cebolinha a gosto.', ' Retire a pele e corte o salmão em cubos; Coloque em uma vasilha e tempere com sal; Corte a cebolas em fatias finas e coloque de molho em um potinho com água gelada e gelo; Retire todas as sementes da pimenta e corte bem; Em um liquidificador, coloque o azeite, o suco de limão, o shoyu e bata muito bem; Despeje esse molho sobre o peixe e adicione a cebola e a pimenta; Misture bem e deixe na geladeira por meia hora; Na hora de servir, coloque cebolinha e coentro picados por cima. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Carne moída com abóbora','300 g de carne moída; 700 g de abóbora (cabótia ou japonesa) cortada em cubos; 1 cebola picada; 1 tomate picado; Salsinha a gosto; ½ copo de água; ½ xícara de chá de molho de tomate; Sal e pimenta-do-reino a gosto.', '  Reúna todos os ingredientes; Leve uma panela ao fogo médio, e, sem óleo, refogue a carne e a cebola; Carne moída com abóbora; Adicione o tomate, a abóbora, o molho de tomate, tampe a panela, e deixe tudo cozinhar por cerca de 15 minutos, ou até a abóbora ficar macia. Se precisar, acrescente um pouco de água para que os ingredientes não grudem na panela; Tempere com salsinha, sal e pimenta; Agora é só servir. Bom apetite! .', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Macarrão com camarão fácil ','250g de camarão; 4 a 5 "favos"de massa integral; Manjericão; Tomatinho cereja; Azeite de oliva; 2 dentes de alho; Sal a gosto', '  Cozinhe a massa por cerca de 8 minutos; Frite o alho rapidamente e adicione o camarão. Deixe cozinhar por 8 minutos também; Junte a passa cozinha ao camarão; Adicione os tomatinhos e o manjericão ! .', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Cestinha de peito de peru com ovo   ','4 fatias de peito de peru cortadas ao meio; 1 colher de sopa de cream cheese; 1 ovo; Sal a gosto; Pimenta-calabresa a gosto; Tomilho fresco a gosto.', ' Disponha as fatias de peito de peru em um ramequim ou xícara que possa ir ao micro-ondas; Certifique-se que as fatias cobriram todo o fundo e as laterais do recipiente, formando uma cestinha;Adicione o cream cheese e o ovo; Fure as gemas com um garfo e tempere com sal; Leve ao micro-ondas em potência alta por 1 minuto e 30 segundos ou até o ovo chegar no ponto de sua preferência; Finalize polvilhando pimenta-calabresa e tomilho fresco; Agora é só servir, bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Ratatouille de forno simples ','1 fio de azeite; 1 cebola pequena picada; 5 dentes de alho pequenos picados; 1 lata de tomate pelado; Sal, orégano, cominho e pimenta a gosto; Um ramo de manjericão; 2 berinjelas médias cortadas em fatias de 0,5cm; 2 abobrinhas italianas médias cortadas em fatias de 0,5cm; 5 tomates italianos médios cortados em fatias de 0,5cm; Temperos a gosto (orégano, sal, azeite, cominho, alecrim, tomilho fresco…)', ' Em uma panela, adicione um fio de azeite e refogue a cebola e o alho; Acrescente o tomate pelado, o sal, o orégano, o cominho, a pimenta, o manjericão, misture e deixe cozinhar por cerca de 5 minutos; Coloque mais um pouco de azeite e reserve; Corte os vegetais; Coloque as fatias de berinjela em um escorredor, salpique bastante sal e deixe desidratar por 30 minutos; Lave bem a berinjela para retirar o sal e seque com um papel toalha; Em uma travessa ou forma, despeje todo o molho espalhando pelo fundo; Faça as camadas na vertical de vegetais: coloque uma fatia de berinjela, uma de abobrinha e uma de tomate. Continue o processo até encher o recipiente; Tempere como preferir, regue com azeite, cubra com papel alumínio e leve ao forno preaquecido a 180º por 30 minutos; Passado esse tempo, aumente o forno para 230º graus, retire o papel alumínio e deixe por mais 20 minutos (os ingredientes devem ficar macios); Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Frango ao molho de laranja à moda chinesa  ','2 peitos de frango cortados em cubos; 1 colher de chá de alho moído; 1/2 colher de chá de páprica; 1 ovo; 2 colheres de sopa de molho de soja; Pimenta a gosto; 1/2 xícara de chá de farinha de trigo; 1/2 xícara de chá de amido de milho; 1 xícara de chá de suco de laranja; 1/4 xícara de chá de mel; 1 colher de sopa de molho de soja; 1 colher de sopa de amido de milho; 2 dentes de alho; 1/2 colher de chá de gengibre', '  Em uma vasilha, tempere o frango com o alho, a páprica, o ovo, o molho de soja e a pimenta. Deixe marinar por 20 minutos; Acrescente a farinha, o amido e misture bem para envolver todos os pedaços;  Em óleo quente, frite o frango, aos poucos, para ficar crocante. Reserve;  Para o molho, em uma panela, coloque todos os ingredientes e cozinhe até engrossar; Adicione o frango e cozinhe por mais alguns minutos; Sirva como preferir e aproveite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Panqueca integral nutritiva  ','1 ovo; 1 xícara de chá de leite; 1/2 xícara de chá de farinha de trigo integral; 1/2 xícara de chá de farinha de aveia; 1 colher de sopa de psyllium;  2 colheres de sopa de azeite de oliva; Sal a gosto', '      Bata todos os ingrediente no liquidificador; Despeje a massa em uma frigideira antiaderente ou untada com azeite;  Cozinhe em fogo médio até dourar; Vire e recheie com ingredientes de sua preferência.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Mingau de aveia e quinoa   ','150ml de leite de amêndoas (ou outro leite); 2 colheres de sopa de aveia; 2 colheres de sopa de quinoa em flocos; 1 colher de chá de xilitol; 1 colher de sobremesa de Whey sem sabor; Banana em rodelas, canela e coco em lascas para finalizar', '    Em uma panela, adicione o leite de amêndoas, a aveia, a quinoa, o xilitol, misture e leve para cozinhar em fogo baixo; Deixe cozinhar até engrossar e desligue; Acrescente o Whey e misture até incorporar; Decore com as rodelas de banana, a canela e o coco; Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Banana assada na airfryer ','1 banana madura; Manteiga a gosto; 1 pitada de canela; Nutella ou pasta de amendoim a gosto', '    Corte a banana ao meio (na vertical) com casca; Pincele um pouco de manteiga e polvilhe a canela por cima das fatias e leve para a airfryer preaquecida a 180 ºC por cerca de 7 minutos ou até dourar bem; Passe Nutella ou pasta de amendoim; Agora é só servir. Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Toast de aveia com ovo e espinafre  ','4 colheres de sopa de aveia em flocos finos; 5 colheres de sopa de água;  Queijo vegetal a gosto;  1 ovo; Espinafre a gosto', '        Misture a aveia e a água em uma vasilha; Deixe descansar da noite para o dia, para que a aveia hidrate na água; No dia seguinte, coloque essa mistura em uma frigideira e espalhe com uma colher, no formato de uma panqueca; Leve ao fogo e cozinhe até dourar; Vire e doure o outro lado; Coloque o queijo vegetal por cima e deixe derreter; Desligue e reserve; Quebre o ovo na frigideira e cozinhe mexendo sempre, até ficar na consistência cremosa de ovo mexido; Adicione o espinafre e cozinhe um pouco; Coloque esse recheio na toast; Dobre ao meio e sirva. Bom apetite', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Sanduíche de frango e cottage  ','1 colher de sobremesa de queijo cottage; 1 colher de sobremesa de cenoura ralada; Sal e pimenta-do-reino a gosto;  2 fatias de pão integral; 100 gramas de peito de frango grelhado sem óleo;  Brotos de alfafa a gosto (ou alface); Fatias de tomate a gosto', '   Reúna todos os ingredientes;  Em um processador, coloque o queijo cottage, a cenoura, o sal, a pimenta e bata até misturar bem e formar uma pastinha;  Passe a pastinha nas fatias de pão e monte o sanduíche: coloque o frango, os brotos de alfafa, as fatias de tomate e feche;  Agora é só servir. ',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Sanduíche vegano colorido  ','1 xícara de espinafre cozido; 1 e 1/2 xícara de água fervente; 6 colheres de sopa de azeite; 1 cebola picada; 3 dentes de alho esmagados; Sal rosa a gosto; Pimenta-do-reino moída na hora a gosto; 1 xícara de beterraba cozida; 1 xícara de cenoura cozida;  Pão de forma', 'No liquidificador, coloque o espinafre e cerca de 1/2 xícara de água fervente; Bata até formar uma pasta e reserve; Aqueça o azeite em uma panela e refogue 1/3 da cebola picada e 1/3 do alho, até dourar; Acrescente a pasta de espinafre e cozinhe por alguns minutos; Tempere com sal e pimenta-do-reino e reserve; Bata a beterraba no liquidificador com 1/2 xícara de água fervente, até formar uma pasta, e reserve; Refogue mais 1/3 da cebola e do alho e adicione a pasta de beterraba;Cozinhe por alguns minutos, tempere com sal e pimenta-do-reino e reserve; Repita o processo com a cenoura, batendo com 1/2 xícara de água no liquidificador e refogando com o restante da cebola e do alho; Tempere com sal e pimenta-do-reino e cozinhe por alguns minutos; Em uma fatia de pão de forma, monte uma camada com cada pasta colorida e feche com outra fatia de pão de forma; Agora é só servir! Bom apetite.', 1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Guacamole fácil','4 avocados maduros; 1 tomate maduro; Suco de 1 limão; Coentro picado a gosto; 2 colheres de sopa de azeite; Sal e pimenta-do-reino a gosto', ' Reúna todos os ingredientes;  Corte os avocados ao meio, no sentido do comprimento, descarte o caroço, retire a casca e corte-os em cubos;  Coloque os avocados cortados em uma tigela, regue-os com o suco do limão e amasse-os com um garfo até formar um purê;  Corte o tomate em cubos pequenos e adicione ao purê de avocados com limão;  Junte o coentro à tigela, e tempere tudo com azeite, sal e pimenta-do-reino;  Misture e sirva na sequência',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Snack fácil de grão-de-bico ','1 xícara de grão-de-bico; Água até cobrir o grão-de-bico; Sal; Páprica picante; Cúrcuma; Chimichurri; Orégano; Azeite de oliva', ' Deixe o grão-de-bico de molho em uma vasilha com água por 12h; Coe a água e cozinhe o grão-de-bico por 10 minutos; Retire a pele do grão-de-bico; Tempere com sal, páprica, cúrcuma, chimichurri e orégano; Regue com azeite de oliva; Asse em forno a 200 graus por 20 a 30 minutos; Abra o forno a cada 10 minutos para mexer;Sirva-se.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Omelete de espinafre simples ','4 ovos; Sal e pimenta-do-reino a gosto; 1 colher de sopa de azeite; 1 dente de alho; 1/2 cebola pequena picada; 2 bolinhas de espinafre congelado (cerca de 100 gramas); 4 fatias queijo mussarela', ' Em um recipiente, adicione os ovos, o sal, a pimenta, bata levemente para se misturar e reserve; Em uma frigideira, coloque o azeite e frite o alho até dourar; Acrescente a cebola e deixe refogar até ela ficar transparente; Coloque o espinafre, tempere com sal, pimenta, misture e deixe cozinhar até secar boa parte da água; Diminua o fogo, adicione os ovos batidos e misture rapidamente com movimento circulares; Tampe a panela e deixe cozinhar até ficar mais firme; Vire a omelete, cubra com fatias de queijo, tampe novamente e deixe no fogo até derreter a mussarela; Agora é só servir. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Creme de abóbora com especiarias','1/2 abóbora japonesa; Óleo a gosto; 1 cebola picada; 1 colher de café de canela em pó; Noz-moscada a gosto; 1 colher de sopa de gengibre ralado; 1 anis-estrelado; 3 cardamomos abertos; 1 pimenta-malagueta; Sal a gosto; Água; 200 ml de creme de leite; Salsinha picada a gosto', '  Reúna todos os ingredientes;  Retire as sementes da abóbora e corte-a em cubos grandes;  Leve uma panela ao fogo médio, coloque o óleo, e refogue a cebola;  Adicione a canela, a noz-moscada, o gengibre, o anis-estrelado, os cardamomos, a pimenta e o sal;  Acrescente a abóbora e deixe refogar um pouco;  Coloque a água até cobrir a abóbora, e deixe cozinhar até que ela comece a desmanchar;  Retire o anis, e transfira o conteúdo da panela para o liquidificador;  Bata até virar um creme, coloque-o na panela, adicione um pouco de água, e deixe cozinhar por cerca de 5 minutos;  Adicione o creme de leite, acerte o tempero, e finalize com a salsinha;  Agora é só servir. Bom apetite! .',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Creme de cenoura e gengibre com frango  ','1 peito de frango; Sal e pimenta-do-reino; Suco de ½ limão; 2 colheres de sopa de óleo gergelim; 1 cebola média picada; 1 talo alho-poró (parte branca) cortado em rodelinhas; 1kg cenoura corta em rodelas (sem casca); 1 colher de chá de cúrcuma; 1 colher de chá de garam masala; 1 gengibre ralado; 500ml caldo legumes; 200ml leite de coco; 1 colher de sopa de azeite', 'Corte o peito de frango em cubos, tempere com sal, pimenta, suco de limão e deixe marinar por cerca de 10 minutos;  Em uma panela, refogue a cebola e o alho-poró no óleo de gergelim; Adicione as cenouras, a cúrcuma, o garam marsala, o gengibre e deixe refogar mais um pouco; Acrescente o caldo de legumes e deixe cozinhar, em fogo médio, até a cenoura ficar macia; Coloque o leite de coco, misture bem e transfira para um liquidificador; Bata até virar um creme homogêneo, volte para a panela em fogo baixo e acerte os temperos; Em outra panela, coloque um pouco de azeite e frite o frango até ficarem bem douradinhos; Transfira o creme para uma travessa e junte o frango; Agora é só servir. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Creme de brócolis com alho-poró ','2 brócolis japonês; 1 cebola; 1 talo de alho-poró; 1 talo de salsão; 500 ml de caldo caseiro de legumes ou de frango; 250 ml de creme de leite fresco; 1 colher de sopa de manteiga; 1 fio de azeite de oliva; Sal a gosto; Pimenta-do-reino a gosto; Noz-moscada a gosto; Cheiro-verde a gosto', 'Em uma panela, coloque a manteiga, o azeite e refogue a cebola, o alho-poró e o salsão até ficarem levemente dourados; Adicione o brócolis, tempere com sal, pimenta e refogue mais um pouco; Junte o caldo quente, tampe e cozinhe até tudo ficar bem amolecido; Transfira para um liquidificar e bata até ficar homogêneo.; Lembre-se de deixar a tampinha menor aberta para sair o vapor; Coloque na panela novamente e acrescente o creme de leite; Ferva e adicione a noz-moscada',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Sopa de tomate fácil  ','Azeite a gosto; ½ cebola grande picada; 1 kg de tomates maduros cortados ao meio; Meio litro de água; 4 folhas pequenas de manjericão; Folha de louro; Sal a gosto', ' Reúna todos os ingredientes;  Leve uma panela ao fogo médio, coloque azeite e refogue a cebola;  Adicione os tomates, a água, o manjericão, o louro, sal e misture; quando levantar fervura, abaixe o fogo e deixe cozinhar por 20 minutos;  Desligue o fogo, espere a sopa ficar morna, retire a folha de louro e bata tudo no liquidificador até homogeneizar;  Peneire a sopa em uma panela e leve-a para cozinhar em fogo médio;  Acerte o sal e mexa até levantar fervura;  Agora é só servir. Bom apetite! ',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Sopa de espinafre com frango low carb','Azeite a gosto; 1 dente de alho amassados; 1/2 cebola picada; 1 filé de frango; 3 chuchus cortados em cubinhos; 3 abobrinhas pequenas cortados em cubinhos; Água fervente; 1 punhado de espinafre cozido; Sal e pimenta a gosto', ' Em uma panela, esquente o azeite e refogue o alho e a cebola; Adicione os filés de frango e refogue mais um pouco; Acrescente o chuchcu, a abobrinha, cubra com água fervente e deixe cozinhar; Assim que os legumes cozinharem, retire o frango e transfira o resto para um liquidificador; Coloque o espinafre também e bata até formar um caldo; Despeje em um recipiente; Desfie ou corte o frango em cubinho, junte com com caldo, tempere com sal e pimenta; Agora é só servir. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Canja de galinha low carb  ','2 litros de água; 1 cebola cortada em cubos; 2 dentes de alho amassados; 2 cenouras médias cortadas em cubos; 1 couve-flor picada; 500 gramas de frango desfiado ou em cubinho; Sal e pimenta-do-reino a gosto; 1/2 xícara de chá salsinha picada', 'Reúna todos os ingredientes;  Em uma panela, coloque a água, a cebola, o alho, a cenoura e deixe cozinhar até a cenoura ficar macia;  Adicione a couve-flor, o frango, o sal, a pimenta, misture bem e deixe cozinhar;  Acrescente a salsinha, misture bem e sirva. ',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Creme de inhame com espinafre ','1/2 cebola grande picada em cubos; 1 dente de alho picado; 150 gramas de inhame cru cortado em cubos; 1/2 xícara de chá de água; 1/2 xícara de chá de espinafre cru com talos; Sal, azeite, pimenta-do-reino e temperos a gosto', 'Em uma panela, esquente um fio de azeite e refogue a cebola e o alho; Adicione o inhame, a água, misture e deixe cozinhar até ficar macio; Transfira para um liquidificador (com a água do cozimento), acrescente o espinafre, os temperos e bata até ficar homogêneo; Volte para o fogo e deixe apurar alguns minutinhos; Agora é só servir. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Pudim de chia com manga ','1 vidro de leite de coco;  1/2 banana-prata; 1 colher de chá de gengibre ralado; 1 colher de sopa de mel; 1/2 copo de iogurte natural; 3 colheres de sopa de sementes de chia; 1 manga média em pedaços; 1 folha de gelatina', 'Em um liquidificador, bata o leite de coco, a banana, o gengibre, o mel e o iogurte; Em um recipiente, coloque a chia, despeje a mistura do liquidificador, mexa bem e reserve; Em um processador, triture as mangas até formar um purê; Junte o purê com a folha de gelatina, misture bem e reserve; Coloque a gelatina no copo e deixe gelar; Assim que firmar, acrescente o pudim de chia e leve na geladeira novamente para firmar; Agora é só servir. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Bolo de banana fit ','2 ovos; 4 bananas-nanicas médias amassadas; Canela a gosto; 1 xícara de chá de aveia em flocos finos;  1 colher de chá de fermento químico em pó', 'Reúna todos os ingredientes;  Em um recipiente, adicione os ovos e bata levemente para eles se misturarem;  Acrescente a banana amassada, a canela, a aveia e mexa bem até ficar homogêneo;  Coloque o fermento e mexa com delicadeza para incorporar;  Transfira para uma forma pequena, untada e leve ao forno preaquecido a 180º graus por cerca de 25 a 30 minutos;  Agora é só servir. Bom apetite!',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Pudim fit de coco com calda de frutas vermelhas  ','2 envelopes de gelatina em pó sem sabor; 500 ml de leite desnatado; 200 g de creme de leite fresco; 200 ml de leite de coco; 100 g de coco seco;  5 colheres de sopa de xilitol; 1 xícara de frutas vermelhas; 1/2 xícara de açúcar de coco; 1/2 xícara de água', '    Hidrate a gelatina conforme as especificações do fabricante; No liquidificador, coloque o leite, o creme de leite, o leite de coco, o coco seco, o xilitol e a gelatina hidratada; Bata muito bem até obter um creme homogêneo; Distribua em forminhas individuais e reserve na geladeira por pelo menos 2 horas; Enquanto isso, para a calda, coloque em uma panela as frutas vermelhas, o açúcar e a água; Cozinhe até o açúcar derreter e a calda engrossar. Deixe esfriar; a hora de servir, desenforme o pudim e despeje a calda por cima. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Smoothie de morango e banana','1 banana; 2 xícaras de chá de morangos; 1/3 de xícara de chá de iogurte natural (de preferência iogurte grego);  Gelo a gosto', 'Corte a banana e os morangos em pedaços menores;  Em um liquidificador, coloque a banana, o morango, o iogurte, o gelo e bata bem;  Caso precise, adicione um pouco de água para ajudar a bater; Transfira o smoothie para uma jarra e sirva. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Torta de maçã fit ','3 maçãs médias com casca e sem miolo; 1/2 colher de chá de canela em pó; Raspas de 1 limão; Suco de 1 limão; 1/2 xícara de chá de amido de milho; 1/3 de xícara de chá de farinha de aveia; 1/2 colher de chá de canela em pó; Pitada de sal; 1/2 colher de sopa de fermento em pó; 1/2 xícara de chá de açúcar demerara; 2 ovos; ¼ de xícara de chá de óleo de coco derretido (ou manteiga);  ¼ de xícara de chá de passas (pretas e brancas); 3 colheres de sopa de flocos de aveia', ' Reúna todos os ingredientes;  Corte as maçãs em fatias (cerca de 2 a 3 mm), transfira para um recipiente, junte a canela, as raspas de limão e o suco também. Misture e reserve;  Em outra tigela, adicione o amido de milho, a farinha de aveia, a canela, o sal, o fermento e misture bem;  Acrescente o açúcar demerara (mas reserve 2 a 3 colheres de sopa para os ovos), misture e reserve;  Em um terceiro recipiente, coloque os ovos, o restante do açúcar reservado, o óleo de coco e misture até ficar homogêneo;  Em uma forma de fundo removível, forre o fundo com as maçãs, salpique um pouco de passas, polvilhe por cima a mistura de farinhas e repita o processo até terminar as maçãs e os secos. Finalize com uma camada de maçãs;  Com a ajuda de uma colher, vá adicionando a mistura de ovos por cima e finalize salpicando os flocos de aveia;  Leve ao forno preaquecido a 180 ºC por cerca de 30 a 40 minutos;  Desenforme e sirva',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Doce de abóbora com coco light ','1 e 1/2 xícara de chá de abóbora (cozida e amassada);  1 xícara de chá de coco ralado; 1 colher de sopa de xilitol (ou stevia, açúcar de coco, mascavo…); Especiarias a gosto (opcional); 1 rama de canela; 3 cravos; 3 anis-estrelado; 1 pitada de pimenta síria; 2 xícaras de chá de leite; 1 colher de chá de canela em pó', 'Em uma panela, adicione a abóbora amassada, o coco, o xilitol, as especiarias, a canela, os cravos, o anis-estrelado e misture bem; Ligue o fogo e vá acrescentando gradualmente o leite e misturando; Deixe ferver por cerca de 5 minutos; Retire os cravos e a rama de canela; Sirva com coco e canela polvilhada por cima. Bom apetite!.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Pudim de chocolate diet  ','200ml de leite de coco; 1 xícara de chá de cacau em pó; 8 bananas (cortadas em rodelas); Óleo de coco para untar', ' Reúna todos os ingredientes;  Em um liquidificador, coloque todos os ingredientes e bata até formar um creme homogêneo;  Transfira para uma panela, ligue no fogo médio, deixe cozinhar, mexendo sempre até reduzir e formar um creme mais firme (cerca de 7 minutos cozinhando);  Passe para uma forma de pudim, untada com óleo de coco e leve para a geladeira por cerca de 2 horas;  Desenforme e sirva. ',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Bolinho de cenoura fit no micro-ondas   ','    80 g de cenoura picada;  1 ovo; 1 colher de eritritol ou outro adoçante; 20 g de farinha de aveia; 3 colheres de sopa de leite; 1 colher de café de fermento; 1/2 scoop de whey de chocolate; 1 colher de sopa de água', '     No liquidificador, coloque a cenoura, ovo, eritritol, farinha de aveia e leite;Bata a mistura até ficar homogênea; Acrescente o fermento e bata apenas para incorporar; Despeje a massa em um recipiente próprio para micro-ondas; Leve ao micro-ondas por 3 minutos; Misture o whey com a água até obter uma textura cremosa; espalhe essa mistura por cima do bolinho; Sirva e bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Muffin fit de nozes com passas ','1 xícara de uva passas; 3 ovos; 1 xícara de farinha de nozes;  1 xícara de farelo de aveia sem glúten; 1/2 xícara óleo de coco; 1/2 xícara água;  1 colher de sopa fermento; 1 colher de sobremesa de mix de especiarias (canela, cravo em pó, noz moscada)', '     Bata as uvas passas no liquidificador; Adicione os ovos, o óleo de coco, as farinhas e a água; Depois de misturar, adicione o fermento e mexa delicadamente com uma colher; Distribua em forminhas de muffin e decore com nozes quebradas; Asse em forno preaquecido a 200 °C por 20-25 minutos até dourar; Agora é só servir! Bom apetite',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Brigadeiro fake vegano  ','500 ml de leite de amêndoas; 2 colheres de sopa de cacau em pó; 2 colheres de sopa de xilitol (adoçante); 1 colher de sopa de óleo de coco;  Extrato de baunilha (opcional);  Pitada de sal', '     Na panela, coloque todos os ingredientes, misture bem e leve ao fogo médio; Vá mexendo sem parar até reduzir e ficar cremoso; Transfira para um recipiente e deixe esfriar; Agora é só servir. Bom apetite.',1);

INSERT INTO tb_receitas(nomeReceita, receita, preparo, id_tipoReceita) VALUES('Mousse de abacate proteico  ','1/2 abacate gelado; 200 ml de leite de macadâmia (leite de coco ou qualquer outro tipo de leite); 1 scoop de Whey Protein sem sabor (opcional); Mel ou adoçante a gosto', ' Coloque tudo em um liquidificador e bata até ficar homogêneo; Transfira para um recipiente e sirva. Bom apetite.',1);

